export const boxes = 40;

export const ctx = document.getElementById('game').getContext("2d");

export const img = new Image()
img.src = "src/images/base.png"

export var tank = {
    x: 8 *boxes,
    y: 15 *boxes,
    shoot: false,
    health: 100
}

export const wall = [
    {x:1* boxes, y:1* boxes},
    {x:2* boxes, y:1* boxes},
    {x:3* boxes, y:1* boxes},
    {x:2* boxes, y:2* boxes},
    {x:2* boxes, y:3* boxes},
    {x:7* boxes, y:1* boxes},
    {x:6* boxes, y:2* boxes},
    {x:8* boxes, y:2* boxes},
    {x:7* boxes, y:2* boxes},
    {x:5* boxes, y:3* boxes},
    {x:6* boxes, y:3* boxes},
    {x:8* boxes, y:3* boxes},
    {x:9* boxes, y:3* boxes},
    {x:10* boxes, y:1* boxes},
    {x:10* boxes, y:2* boxes},
    {x:10* boxes, y:3* boxes},
    {x:11* boxes, y:2* boxes},
    {x:12* boxes, y:1* boxes},
    {x:12* boxes, y:2* boxes},
    {x:12* boxes, y:3* boxes},
    {x:13* boxes, y:1* boxes},
    {x:13* boxes, y:2* boxes},
    {x:13* boxes, y:3* boxes},
    {x:14* boxes, y:2* boxes},
    {x:15* boxes, y:1* boxes},
    {x:15* boxes, y:3* boxes},
    {x:9* boxes, y:5* boxes},
    {x:9* boxes, y:6* boxes},
    {x:12* boxes, y:5* boxes},
    {x:13* boxes, y:5* boxes},
    {x:14* boxes, y:5* boxes},
    {x:15* boxes, y:5* boxes},
    {x:12* boxes, y:6* boxes},
    {x:13* boxes, y:6* boxes},
    {x:14* boxes, y:6* boxes},
    {x:15* boxes, y:6* boxes},//
    {x:0* boxes, y:6* boxes},
    {x:1* boxes, y:6* boxes},
    {x:2* boxes, y:6* boxes},
    {x:3* boxes, y:6* boxes},
    {x:4* boxes, y:6* boxes},
    {x:5* boxes, y:6* boxes},
    {x:6* boxes, y:6* boxes},
    {x:0* boxes, y:7* boxes},
    {x:1* boxes, y:7* boxes},
    {x:2* boxes, y:7* boxes},
    {x:3* boxes, y:7* boxes},
    {x:4* boxes, y:7* boxes},
    {x:5* boxes, y:7* boxes},
    {x:6* boxes, y:7* boxes},
    {x:10* boxes, y:8* boxes},
    {x:10* boxes, y:9* boxes},
    {x:10* boxes, y:10* boxes},
    {x:10* boxes, y:11* boxes},
    {x:10* boxes, y:12* boxes},
    {x:9* boxes, y:13* boxes},
    {x:9* boxes, y:14* boxes},
    {x:9* boxes, y:15* boxes},
    {x:5* boxes, y:14* boxes},
    {x:6* boxes, y:14* boxes},
    {x:5* boxes, y:15* boxes},
    {x:6* boxes, y:15* boxes},//
    {x:0* boxes, y:10* boxes},
    {x:1* boxes, y:10* boxes},
    {x:0* boxes, y:11* boxes},
    {x:1* boxes, y:11* boxes},//
    {x:14* boxes, y:13* boxes},
    {x:15* boxes, y:13* boxes},
    {x:13* boxes, y:13* boxes},
    {x:13* boxes, y:14* boxes},
    {x:13* boxes, y:15* boxes},//
    {x:4* boxes, y:10* boxes},
    {x:5* boxes, y:10* boxes},
    {x:6* boxes, y:10* boxes},
    {x:4* boxes, y:11* boxes},
    {x:6* boxes, y:11* boxes},
    {x:6* boxes, y:12* boxes},
    {x:4* boxes, y:12* boxes},
    {x:5* boxes, y:12* boxes},//
    {x:0* boxes, y:13* boxes},
    {x:1* boxes, y:13* boxes},
    {x:0* boxes, y:14* boxes},
    {x:1* boxes, y:14* boxes},
    {x:0* boxes, y:15* boxes},
    {x:1* boxes, y:15* boxes},
    {x:2* boxes, y:15* boxes},//
    {x:13* boxes, y:9* boxes},
    {x:14* boxes, y:9* boxes},
    {x:15* boxes, y:9* boxes},
    {x:15* boxes, y:10* boxes},
    {x:15* boxes, y:11* boxes},
    {x:13* boxes, y:10* boxes},
    {x:13* boxes, y:11* boxes},
    {x:14* boxes, y:10* boxes},
    {x:14* boxes, y:11* boxes}
]